/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : string,
  'name' : string,
  'unlocked' : boolean,
  'unlockedTimestamp' : Time,
}
export interface MealPlan { 'weekStartDate' : string, 'planData' : string }
export interface Recipe {
  'id' : string,
  'title' : string,
  'difficulty' : string,
  'cuisineType' : string,
  'cookTime' : bigint,
  'description' : string,
  'nutritionInfo' : string,
  'steps' : Array<string>,
  'ingredients' : Array<string>,
}
export interface SessionDataView {
  'recipes' : Array<Recipe>,
  'achievements' : Array<Achievement>,
  'mealPlan' : [] | [MealPlan],
}
export type Time = bigint;
export interface _SERVICE {
  'getAchievements' : ActorMethod<[string], Array<Achievement>>,
  'getMealPlan' : ActorMethod<[string], [] | [MealPlan]>,
  'getOrCreateSession' : ActorMethod<[string], undefined>,
  'getSavedRecipes' : ActorMethod<[string], Array<Recipe>>,
  'getSessionData' : ActorMethod<[string], [] | [SessionDataView]>,
  'removeRecipe' : ActorMethod<[string, string], undefined>,
  'saveAchievement' : ActorMethod<[string, Achievement], undefined>,
  'saveMealPlan' : ActorMethod<[string, MealPlan], undefined>,
  'saveRecipe' : ActorMethod<[string, Recipe], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];