/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Achievement = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'unlocked' : IDL.Bool,
  'unlockedTimestamp' : Time,
});
export const MealPlan = IDL.Record({
  'weekStartDate' : IDL.Text,
  'planData' : IDL.Text,
});
export const Recipe = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'difficulty' : IDL.Text,
  'cuisineType' : IDL.Text,
  'cookTime' : IDL.Nat,
  'description' : IDL.Text,
  'nutritionInfo' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'ingredients' : IDL.Vec(IDL.Text),
});
export const SessionDataView = IDL.Record({
  'recipes' : IDL.Vec(Recipe),
  'achievements' : IDL.Vec(Achievement),
  'mealPlan' : IDL.Opt(MealPlan),
});

export const idlService = IDL.Service({
  'getAchievements' : IDL.Func([IDL.Text], [IDL.Vec(Achievement)], ['query']),
  'getMealPlan' : IDL.Func([IDL.Text], [IDL.Opt(MealPlan)], ['query']),
  'getOrCreateSession' : IDL.Func([IDL.Text], [], []),
  'getSavedRecipes' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
  'getSessionData' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SessionDataView)],
      ['query'],
    ),
  'removeRecipe' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveAchievement' : IDL.Func([IDL.Text, Achievement], [], []),
  'saveMealPlan' : IDL.Func([IDL.Text, MealPlan], [], []),
  'saveRecipe' : IDL.Func([IDL.Text, Recipe], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Achievement = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'unlocked' : IDL.Bool,
    'unlockedTimestamp' : Time,
  });
  const MealPlan = IDL.Record({
    'weekStartDate' : IDL.Text,
    'planData' : IDL.Text,
  });
  const Recipe = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'difficulty' : IDL.Text,
    'cuisineType' : IDL.Text,
    'cookTime' : IDL.Nat,
    'description' : IDL.Text,
    'nutritionInfo' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'ingredients' : IDL.Vec(IDL.Text),
  });
  const SessionDataView = IDL.Record({
    'recipes' : IDL.Vec(Recipe),
    'achievements' : IDL.Vec(Achievement),
    'mealPlan' : IDL.Opt(MealPlan),
  });
  
  return IDL.Service({
    'getAchievements' : IDL.Func([IDL.Text], [IDL.Vec(Achievement)], ['query']),
    'getMealPlan' : IDL.Func([IDL.Text], [IDL.Opt(MealPlan)], ['query']),
    'getOrCreateSession' : IDL.Func([IDL.Text], [], []),
    'getSavedRecipes' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
    'getSessionData' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SessionDataView)],
        ['query'],
      ),
    'removeRecipe' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveAchievement' : IDL.Func([IDL.Text, Achievement], [], []),
    'saveMealPlan' : IDL.Func([IDL.Text, MealPlan], [], []),
    'saveRecipe' : IDL.Func([IDL.Text, Recipe], [], []),
  });
};

export const init = ({ IDL }) => { return []; };