/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MealPlan {
    weekStartDate: string;
    planData: string;
}
export interface Recipe {
    id: string;
    title: string;
    difficulty: string;
    cuisineType: string;
    cookTime: bigint;
    description: string;
    nutritionInfo: string;
    steps: Array<string>;
    ingredients: Array<string>;
}
export type Time = bigint;
export interface SessionDataView {
    recipes: Array<Recipe>;
    achievements: Array<Achievement>;
    mealPlan?: MealPlan;
}
export interface Achievement {
    id: string;
    name: string;
    unlocked: boolean;
    unlockedTimestamp: Time;
}
export interface backendInterface {
    getAchievements(sessionId: string): Promise<Array<Achievement>>;
    getMealPlan(sessionId: string): Promise<MealPlan | null>;
    getOrCreateSession(sessionId: string): Promise<void>;
    getSavedRecipes(sessionId: string): Promise<Array<Recipe>>;
    getSessionData(sessionId: string): Promise<SessionDataView | null>;
    removeRecipe(sessionId: string, recipeId: string): Promise<void>;
    saveAchievement(sessionId: string, achievement: Achievement): Promise<void>;
    saveMealPlan(sessionId: string, mealPlan: MealPlan): Promise<void>;
    saveRecipe(sessionId: string, recipe: Recipe): Promise<void>;
}
import type { Achievement as _Achievement, MealPlan as _MealPlan, Recipe as _Recipe, SessionDataView as _SessionDataView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAchievements(arg0: string): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements(arg0);
            return result;
        }
    }
    async getMealPlan(arg0: string): Promise<MealPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealPlan(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealPlan(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateSession(arg0);
            return result;
        }
    }
    async getSavedRecipes(arg0: string): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedRecipes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedRecipes(arg0);
            return result;
        }
    }
    async getSessionData(arg0: string): Promise<SessionDataView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionData(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionData(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeRecipe(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeRecipe(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeRecipe(arg0, arg1);
            return result;
        }
    }
    async saveAchievement(arg0: string, arg1: Achievement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAchievement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAchievement(arg0, arg1);
            return result;
        }
    }
    async saveMealPlan(arg0: string, arg1: MealPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMealPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMealPlan(arg0, arg1);
            return result;
        }
    }
    async saveRecipe(arg0: string, arg1: Recipe): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRecipe(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRecipe(arg0, arg1);
            return result;
        }
    }
}
function from_candid_SessionDataView_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionDataView): SessionDataView {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MealPlan]): MealPlan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionDataView]): SessionDataView | null {
    return value.length === 0 ? null : from_candid_SessionDataView_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recipes: Array<_Recipe>;
    achievements: Array<_Achievement>;
    mealPlan: [] | [_MealPlan];
}): {
    recipes: Array<Recipe>;
    achievements: Array<Achievement>;
    mealPlan?: MealPlan;
} {
    return {
        recipes: value.recipes,
        achievements: value.achievements,
        mealPlan: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.mealPlan))
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
